specfile_path: libreport.spec
synced_files:
  - .packit.yml
  - libreport.spec
upstream_package_name: libreport
upstream_project_url: https://github.com/abrt/libreport
downstream_package_name: libreport
jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branch: fedora-all
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
